### ISSUE TITLE
Networking EPIC

### ISSUE THREAD

**Issue by dmikey** [ovrclk/akash#1340]
- [ ] https://github.com/ovrclk/akash/issues/1339
- [ ] https://github.com/ovrclk/akash/issues/1303
- [ ] https://github.com/ovrclk/akash/issues/1276
