### ISSUE TITLE
feat: Use Stringer code generator for static type conversions

### ISSUE THREAD

**Issue by Ropes** [ovrclk/akash#665]
There are multiple type mappings where a string is converted into a static type or converse. 

Example of mapping strings to types in one function, and then needing to have inverse functionality. https://github.com/ovrclk/akash/pull/657#discussion_r439154127

Generating the inverse lookup code statically with [stringer](https://godoc.org/golang.org/x/tools/cmd/stringer).

### TODO
* [ ] Add stringer to build tools
  * Vendor vs local install?
* [ ] Mark codepaths needing to be generated
* [ ] Tooling to generate static code

**Comment by akhilkumarpilli** [comment]
@boz, Do I need to generate stringer code manually wherever needed by running stringer command?
