### ISSUE TITLE
testing: E2E validation of app run by Provider

### ISSUE THREAD

**Issue by Ropes** [ovrclk/akash#777]
**Goal**: Single test execution which validates that our all components of the Akash stack are functioning correctly and running an example App is successful. To detect when a change causes a break in E2E functionality; every component should provide useful logging to make the cause of the failure easily identifiable between each service. 

## Integration Testing

Currently we have basic blockchain testing of `akashctl` and `akashd` in the `integration/` package. This ~~could theoretically be~~ has been extended to test running the `provider`, however to provide full E2E running App validation some minified k8s API would need to support the provider process.(currently running against the same `kind` env that we use in `_run/kube`).

## Service Testing

Testing via the indipendent services orchestrated via containers or bash scripts. Ultimately a close approximation to what will be running, and a true test of the services. The downside is that it requires a full orchestration system which also requires maintenance and sorting through the processes output can waste an incredible amount of time.

## Integration Testing Implemented

Thus far work done on expanding the capability of our `integration/` testing package. 

* `provider` is now able to run with equivalent configuration to how it's handled in `_run/kube`
  * Re-using the `integration` package's Deployment test code, the `provider` is bidding on Orders.
* Had to hack up the `cosmos-sdk/tests` package to support processes where EnvVars needed to be set.
  * Since all this code is going to need a refactor, I've done a quick copy-hack in the `integration/` package.
* Various improvements to cleanup and common `test_helpers.go`

### TODO:
* [ ] Manage `kind` environment for integration tests. Potentially with `integration` package helpers.
* [ ] Send manifest to Provider
* [ ] Assert that application is deployed
* [ ] Assert that the application is available and responds
* [ ] Teardown

**Comment by boz** [comment]
There are existing `kind` setup scripts, used [here](https://github.com/ovrclk/akash/blob/faf26a8704ecf39730597254b9633d3da6542ca7/.github/workflows/k8s-integration.yaml#L16-L20) in CI and also in `_run/single`, `_run/kube`.

**Comment by Ropes** [comment]
Hopefully will reuse `_run/kube` and the CI tooling!

As is right now I've got the `integration` package bootstrapping the Provider, creating Deployments, validating won Leases, and sending manifest to the provider which does create the `web` container. However running into issues with the spec, or tied to the issue we have with how `kind` got created.(Still de-:bug: 'ing)

```                                                                                                            
        I[2020-08-04|18:16:15.737] data received                                module=manifest-manager deployment=akash14976z53yc0j7thekzsksyu0wun30l7e3p0kun3/7 version="\ufffd\ufffdZ\ufff$
@u\ufffd+d\ufffd\ufffd\u0014h\ufffd\ufffd\ufffdw\ufffd*\ufffd]4\ufffd\ufffdl\ufffd\u0019E=Ø"                                                                                                  
        I[2020-08-04|18:16:25.944] manifest received                            module=manifest-manager deployment=akash14976z53yc0j7thekzsksyu0wun30l7e3p0kun3/7                             
        D[2020-08-04|18:16:25.944] requests valid                               module=manifest-manager deployment=akash14976z53yc0j7thekzsksyu0wun30l7e3p0kun3/7 num-requests=1              
        D[2020-08-04|18:16:25.944] publishing manifest received                 module=manifest-manager deployment=akash14976z53yc0j7thekzsksyu0wun30l7e3p0kun3/7 num-leases=1                
        I[2020-08-04|18:16:25.944] manifest received                            module=provider-cluster cmp=service                                                                           
        D[2020-08-04|18:16:26.039] provider/cluster/kube/builder: created rules module=kube-builder rules=[]                                                                                  
        E[2020-08-04|18:16:26.047] applying ingress                             module=provider-cluster-kube err="Ingress.extensions \"web\" is invalid: spec: Invalid value: []networking.Ing
ressRule(nil): either `backend` or `rules` must be specified" lease=akash14976z53yc0j7thekzsksyu0wun30l7e3p0kun3/7/1/1/akash1tscyn85n5j9t6mr90ucxhz3rxyghlhh20hc75l service=web expose="&{Port
:80 ExternalPort:0 Proto: Service: Global:true Hosts:[]}"                                                                                                                                     
        E[2020-08-04|18:16:26.047] execution error                              module=provider-cluster cmp=service cmp=deployment-manager lease=akash14976z53yc0j7thekzsksyu0wun30l7e3p0kun3/
7/1/1/akash1tscyn85n5j9t6mr90ucxhz3rxyghlhh20hc75l manifest-group=global state=deploy-active err="Ingress.extensions \"web\" is invalid: spec: Invalid value: []networking.IngressRule(nil): e
ither `backend` or `rules` must be specified"                                                                                                                                                 
        D[2020-08-04|18:16:26.047] deploy complete                              module=provider-cluster cmp=service cmp=deployment-manager lease=akash14976z53yc0j7thekzsksyu0wun30l7e3p0kun3/
7/1/1/akash1tscyn85n5j9t6mr90ucxhz3rxyghlhh20hc75l manifest-group=global                                                                                 
```

Otherwise fairly happy with the implementation, and covers a lot of the codebase! I did have to hack around limitations in `cosmos-sdk/tests` package, which results in some duplicated implementations for modification. However we're going to have to refactor this whole package once 0.40 lands, hopefully for the better.

**Comment by boz** [comment]
There's no hostname for service `web`.  See (just created) #778 point 1.

**Comment by Ropes** [comment]
App manifest is being deployed to cluster and running in `kind` from the `integration` tests! 

Still need to get it running in GH actions and finalize some cleanup and assertion logic.

**Comment by Ropes** [comment]
Dealing with some frustrating validation of the container's web service from the `integration` tests. 

Cleanup of containers in `kind` cluster handled.

**Comment by boz** [comment]
What are the issues you're hitting?
